trigger:
- none

name: $(Build.DefinitionName)-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PreDeployment
  displayName: Pre-Deployment
  jobs:
  - job: Packages
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true
        architecture: 'x64'
      displayName: Use specific Python version in line with Lambda Runtime + Lambda Layer Runtime

    - bash: |
        python3 -m pip install -t ./python -r requirements.txt
        zip -r $(Build.ArtifactStagingDirectory)/discord_bot_packages.zip python
      displayName: Create lambda layer package
      workingDirectory: $(Pipeline.Workspace)/s

    - bash: |
        zip -r $(Build.ArtifactStagingDirectory)/lambda_deployment_package.zip lambda_files/ -j
      displayName: Create deployment package from lambda code
      workingDirectory: $(Pipeline.Workspace)/s

    - publish: $(Build.ArtifactStagingDirectory)/discord_bot_packages.zip
      artifact: Lambda_Packages
      displayName: Publish lambda packages artifact

    - publish: $(Build.ArtifactStagingDirectory)/lambda_deployment_package.zip
      artifact: Lambda_Code
      displayName: Publish lambda code artifact

  - job: Terraform
    dependsOn: Packages
    displayName: Create Terraform plan
    steps:
    - checkout: self
    - download: current
      artifact: Lambda_Packages
      displayName: Download lambda layer package

    - download: current
      artifact: Lambda_Code
      displayName: Download lambda deployment package

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: Install latest version of Terraform on agent

    - task: AzureKeyVault@2
      displayName: Retrieve AWS Credentials from Azure Key Vault
      inputs:
        azureSubscription: 'Azure RM Service Connection'
        KeyVaultName: 'AWSCredentialsVault'
        SecretsFilter: 'AWSAccessKey, AWSSecretKey, API-KEY, PUBLIC-KEY'
        RunAsPreJob: false


    - bash: |
        terraform init \
        -backend-config="bucket=$(BACKEND_BUCKET)" \
        -backend-config="key=$(TFSTATE_KEY)" \
        -backend-config="region=$(REGION)" 
      env:
        AWS_SECRET_ACCESS_KEY: $(AWSSecretKey)
        AWS_ACCESS_KEY_ID: $(AWSAccessKey)
        REGION: $(region)
        BACKEND_BUCKET: $(backend_bucket)
        TFSTATE_KEY: $(tfstate_key)
      displayName: Initialize terraform working directory
      workingDirectory: $(Pipeline.Workspace)/s/terraform_code

    - bash: |
        terraform plan -out=$(Build.ArtifactStagingDirectory)/plan.json \
        -var 'lambda_packages_bucket=$(LAMBDA_PACKAGES_BUCKET)' \
        -var 'lambda_name=$(LAMBDA_NAME)' \
        -var 'dynamodb_table_name=$(DYNAMODB_TABLE_NAME)' \
        -var 'lambda_layer_zip_path=$(Pipeline.Workspace)/Lambda_Packages/discord_bot_packages.zip' \
        -var 'lambda_code_zip_path=$(Pipeline.Workspace)/Lambda_Code/lambda_deployment_package.zip' \
        -var 'API_KEY=$(API-KEY)' \
        -var 'PUBLIC_KEY=$(PUBLIC-KEY)' \
        -var 'WEBHOOK_URL=$(WEBHOOK_URL)'
      env:
        AWS_SECRET_ACCESS_KEY: $(AWSSecretKey)
        AWS_ACCESS_KEY_ID: $(AWSAccessKey)
        LAMBDA_PACKAGES_BUCKET: $(lambda_packages_bucket)
        LAMBDA_NAME: $(lambda_name)
        DYNAMODB_TABLE_NAME: $(dynamodb_table_name)
        PUBLIC-KEY: $(PUBLIC-KEY)
        API-KEY: $(API-KEY)
        WEBHOOK_URL: $(WEBHOOK_URL)
      displayName: Run a terraform plan command and produce plan artifact
      workingDirectory: $(Pipeline.Workspace)/s/terraform_code

    - publish: $(Build.ArtifactStagingDirectory)/plan.json
      artifact: terraform_plan
      displayName: Publish terraform plan for consumption

- stage: Deployment
  jobs:
  - job: Deploy
    displayName: Run terraform apply
    steps:
    - task: AzureKeyVault@2
      displayName: Retrieve AWS Credentials from Azure Key Vault
      inputs:
        azureSubscription: 'Azure RM Service Connection'
        KeyVaultName: 'AWSCredentialsVault'
        SecretsFilter: 'AWSAccessKey, AWSSecretKey, API-KEY, PUBLIC-KEY'
        RunAsPreJob: false
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: Install latest version of Terraform on agent
    
    - download: current
      artifact: terraform_plan
      displayName: Download terraform plan
    - download: current
      artifact: Lambda_Packages
      displayName: Download Lambda Layer package
    - download: current
      artifact: Lambda_Code
      displayName: Download Lambda deployment package
    
    - bash: |
        terraform init \
        -backend-config="bucket=$(BACKEND_BUCKET)" \
        -backend-config="key=$(TFSTATE_KEY)" \
        -backend-config="region=$(REGION)" 
        terraform apply $(Pipeline.Workspace)/terraform_plan/plan.json
      env:
        AWS_SECRET_ACCESS_KEY: $(AWSSecretKey)
        AWS_ACCESS_KEY_ID: $(AWSAccessKey)
        REGION: $(region)
        BACKEND_BUCKET: $(backend_bucket)
        TFSTATE_KEY: $(tfstate_key)
      displayName: Terraform apply
      workingDirectory: $(Build.SourcesDirectory)/terraform_code
